"""initial_schema

Revision ID: 1d3b3aad6681
Revises: 
Create Date: 2026-05-21 20:33:04.733947

"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '1d3b3aad6681'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_folder',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=20), server_default='', nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('system', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('full_path', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tb_folder.id'], name=op.f('fk_tb_folder_parent_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_folder'))
    )
    op.create_index(op.f('ix_tb_folder_created_at'), 'tb_folder', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_folder_is_active'), 'tb_folder', ['is_active'], unique=False)
    op.create_index(op.f('ix_tb_folder_parent_id'), 'tb_folder', ['parent_id'], unique=False)
    op.create_table('tb_folder_audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=False),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('ip_address', sa.String(length=45), server_default='', nullable=False),
    sa.Column('user_agent', sa.String(length=500), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_folder_audit_log'))
    )
    op.create_index('ix_tb_folder_audit_log_action_created_at', 'tb_folder_audit_log', ['action', 'created_at'], unique=False)
    op.create_index('ix_tb_folder_audit_log_created_at', 'tb_folder_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_folder_audit_log_target_id'), 'tb_folder_audit_log', ['target_id'], unique=False)
    op.create_index('ix_tb_folder_audit_log_target_id_created_at', 'tb_folder_audit_log', ['target_id', 'created_at'], unique=False)
    op.create_table('tb_procedure_asset',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('source_meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_procedure_asset')),
    sa.UniqueConstraint('sha256', name=op.f('uq_tb_procedure_asset_sha256'))
    )
    op.create_index(op.f('ix_tb_procedure_asset_created_at'), 'tb_procedure_asset', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_procedure_asset_is_active'), 'tb_procedure_asset', ['is_active'], unique=False)
    op.create_table('tb_procedure_audit_log',
    sa.Column('procedure_group_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=False),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('ip_address', sa.String(length=45), server_default='', nullable=False),
    sa.Column('user_agent', sa.String(length=500), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_procedure_audit_log'))
    )
    op.create_index('ix_tb_procedure_audit_log_action_created_at', 'tb_procedure_audit_log', ['action', 'created_at'], unique=False)
    op.create_index('ix_tb_procedure_audit_log_created_at', 'tb_procedure_audit_log', ['created_at'], unique=False)
    op.create_index('ix_tb_procedure_audit_log_group_id_created_at', 'tb_procedure_audit_log', ['procedure_group_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tb_procedure_audit_log_procedure_group_id'), 'tb_procedure_audit_log', ['procedure_group_id'], unique=False)
    op.create_index(op.f('ix_tb_procedure_audit_log_target_id'), 'tb_procedure_audit_log', ['target_id'], unique=False)
    op.create_index('ix_tb_procedure_audit_log_target_id_created_at', 'tb_procedure_audit_log', ['target_id', 'created_at'], unique=False)
    op.create_table('tb_procedure_field',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('required', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('validation_rules', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('show_on_cover', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_procedure_field')),
    sa.UniqueConstraint('key', name=op.f('uq_tb_procedure_field_key'))
    )
    op.create_index(op.f('ix_tb_procedure_field_created_at'), 'tb_procedure_field', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_procedure_field_is_active'), 'tb_procedure_field', ['is_active'], unique=False)
    op.create_table('tb_procedure_settings',
    sa.Column('enable_version_control', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('enable_approval_workflow', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('max_version_number', sa.Integer(), server_default='100', nullable=False),
    sa.Column('auto_archive_days', sa.Integer(), server_default='365', nullable=False),
    sa.Column('require_read_confirmation', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('default_risk_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('default_quality_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_procedure_settings'))
    )
    op.create_index(op.f('ix_tb_procedure_settings_created_at'), 'tb_procedure_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_procedure_settings_is_active'), 'tb_procedure_settings', ['is_active'], unique=False)
    op.create_table('tb_folder_sequence',
    sa.Column('folder_id', sa.String(length=36), nullable=False),
    sa.Column('current_value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sequence_digits', sa.Integer(), server_default='5', nullable=False),
    sa.Column('reset_period', sa.String(length=20), server_default='never', nullable=False),
    sa.Column('last_reset_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['tb_folder.id'], name=op.f('fk_tb_folder_sequence_folder_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_folder_sequence'))
    )
    op.create_index(op.f('ix_tb_folder_sequence_created_at'), 'tb_folder_sequence', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_folder_sequence_folder_id'), 'tb_folder_sequence', ['folder_id'], unique=True)
    op.create_index(op.f('ix_tb_folder_sequence_is_active'), 'tb_folder_sequence', ['is_active'], unique=False)
    op.create_table('tb_procedure',
    sa.Column('procedure_group_id', sa.String(length=36), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('version_change_log', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('read_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('custom_values', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('quality_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('level_of_use', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version_update_notes', sa.Text(), server_default='', nullable=False),
    sa.Column('deprecated_from_folder_id', sa.String(length=36), nullable=True),
    sa.Column('deprecated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('deprecated_by', sa.String(length=128), nullable=True),
    sa.Column('archived_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['tb_folder.id'], name=op.f('fk_tb_procedure_folder_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_procedure'))
    )
    op.create_index(op.f('ix_tb_procedure_created_at'), 'tb_procedure', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_procedure_folder_id'), 'tb_procedure', ['folder_id'], unique=False)
    op.create_index(op.f('ix_tb_procedure_is_active'), 'tb_procedure', ['is_active'], unique=False)
    op.create_index(op.f('ix_tb_procedure_is_current'), 'tb_procedure', ['is_current'], unique=False)
    op.create_index(op.f('ix_tb_procedure_procedure_group_id'), 'tb_procedure', ['procedure_group_id'], unique=False)
    op.create_index(op.f('ix_tb_procedure_status'), 'tb_procedure', ['status'], unique=False)
    op.create_table('tb_procedure_asset_reference',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('procedure_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['tb_procedure_asset.id'], name=op.f('fk_tb_procedure_asset_reference_asset_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['procedure_id'], ['tb_procedure.id'], name=op.f('fk_tb_procedure_asset_reference_procedure_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_procedure_asset_reference'))
    )
    op.create_index('ix_tb_procedure_asset_reference_asset_id', 'tb_procedure_asset_reference', ['asset_id'], unique=False)
    op.create_index('ix_tb_procedure_asset_reference_procedure_id', 'tb_procedure_asset_reference', ['procedure_id'], unique=False)
    op.create_index('uq_tb_procedure_asset_reference_asset_id_procedure_id', 'tb_procedure_asset_reference', ['asset_id', 'procedure_id'], unique=True)
    op.create_table('tb_procedure_attachment',
    sa.Column('procedure_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['tb_procedure.id'], name=op.f('fk_tb_procedure_attachment_procedure_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_procedure_attachment'))
    )
    op.create_index(op.f('ix_tb_procedure_attachment_created_at'), 'tb_procedure_attachment', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_procedure_attachment_is_active'), 'tb_procedure_attachment', ['is_active'], unique=False)
    op.create_index('ix_tb_procedure_attachment_procedure_id', 'tb_procedure_attachment', ['procedure_id'], unique=False)
    op.create_index('ix_tb_procedure_attachment_storage_path', 'tb_procedure_attachment', ['storage_path'], unique=False)
    op.create_table('tb_procedure_chapter',
    sa.Column('procedure_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('code', sa.String(length=50), server_default='', nullable=False),
    sa.Column('content_type', sa.String(length=20), server_default='chapter', nullable=False),
    sa.Column('rich_content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), server_default='', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('mark_status', sa.String(length=20), server_default='unmarked', nullable=False),
    sa.Column('skip_numbering', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('conversion_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tb_procedure_chapter.id'], name=op.f('fk_tb_procedure_chapter_parent_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['procedure_id'], ['tb_procedure.id'], name=op.f('fk_tb_procedure_chapter_procedure_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_procedure_chapter'))
    )
    op.create_index('ix_tb_procedure_chapter_content_type', 'tb_procedure_chapter', ['content_type'], unique=False)
    op.create_index(op.f('ix_tb_procedure_chapter_created_at'), 'tb_procedure_chapter', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_procedure_chapter_is_active'), 'tb_procedure_chapter', ['is_active'], unique=False)
    op.create_index('ix_tb_procedure_chapter_mark_status', 'tb_procedure_chapter', ['mark_status'], unique=False)
    op.create_index('ix_tb_procedure_chapter_parent_id', 'tb_procedure_chapter', ['parent_id'], unique=False)
    op.create_index('ix_tb_procedure_chapter_procedure_id_sort_order', 'tb_procedure_chapter', ['procedure_id', 'sort_order'], unique=False)
    op.create_table('tb_procedure_step',
    sa.Column('procedure_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), server_default='', nullable=False),
    sa.Column('code', sa.String(length=50), server_default='', nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), server_default='', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skip_numbering', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), server_default='', nullable=False),
    sa.Column('caution', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), server_default='', nullable=False),
    sa.Column('warning', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), server_default='', nullable=False),
    sa.Column('expected_output', sa.Text(), server_default='', nullable=False),
    sa.Column('attachment_marks', sa.JSON(), nullable=False),
    sa.Column('require_confirmation', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['tb_procedure_chapter.id'], name=op.f('fk_tb_procedure_step_chapter_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['procedure_id'], ['tb_procedure.id'], name=op.f('fk_tb_procedure_step_procedure_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_procedure_step'))
    )
    op.create_index('ix_tb_procedure_step_chapter_id', 'tb_procedure_step', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_tb_procedure_step_created_at'), 'tb_procedure_step', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_procedure_step_is_active'), 'tb_procedure_step', ['is_active'], unique=False)
    op.create_index('ix_tb_procedure_step_procedure_id_sort_order', 'tb_procedure_step', ['procedure_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###

    # --- MySQL 生成列：模拟 partial-unique 约束 ---
    # SQLite（测试）不创建，由 service 层 check-then-act 守卫；MySQL 作并发后盾。
    # 这些列只存在于迁移、不在 ORM metadata，已在 env.py include_object 中忽略。
    if op.get_bind().dialect.name == "mysql":
        # tb_folder：同 parent 下 active name 唯一（→ 全路径唯一）
        op.execute(
            "ALTER TABLE tb_folder ADD COLUMN active_unique_key VARCHAR(150) "
            "GENERATED ALWAYS AS (CASE WHEN is_active THEN "
            "CONCAT(COALESCE(parent_id, ''), '::', name) END) STORED"
        )
        op.execute(
            "ALTER TABLE tb_folder ADD CONSTRAINT uq_tb_folder_active_parent_name "
            "UNIQUE (active_unique_key)"
        )
        # tb_procedure：active (code, version) 唯一
        op.execute(
            "ALTER TABLE tb_procedure ADD COLUMN active_code_version VARCHAR(150) "
            "GENERATED ALWAYS AS (CASE WHEN is_active THEN "
            "CONCAT(code, '::', version) END) STORED"
        )
        op.execute(
            "ALTER TABLE tb_procedure ADD CONSTRAINT uq_tb_procedure_active_code_version "
            "UNIQUE (active_code_version)"
        )
        # tb_procedure：同 group 仅一条 is_current=TRUE（active）
        op.execute(
            "ALTER TABLE tb_procedure ADD COLUMN current_guard VARCHAR(36) "
            "GENERATED ALWAYS AS (CASE WHEN (is_current AND is_active) "
            "THEN procedure_group_id END) STORED"
        )
        op.execute(
            "ALTER TABLE tb_procedure ADD CONSTRAINT uq_tb_procedure_current_guard "
            "UNIQUE (current_guard)"
        )
        # tb_procedure：同 group 仅一条 DRAFT（Q224，根治并发竞态）
        op.execute(
            "ALTER TABLE tb_procedure ADD COLUMN draft_guard VARCHAR(36) "
            "GENERATED ALWAYS AS (CASE WHEN (status = 'DRAFT' AND is_active) "
            "THEN procedure_group_id END) STORED"
        )
        op.execute(
            "ALTER TABLE tb_procedure ADD CONSTRAINT uq_tb_procedure_draft_guard "
            "UNIQUE (draft_guard)"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tb_procedure_step_procedure_id_sort_order', table_name='tb_procedure_step')
    op.drop_index(op.f('ix_tb_procedure_step_is_active'), table_name='tb_procedure_step')
    op.drop_index(op.f('ix_tb_procedure_step_created_at'), table_name='tb_procedure_step')
    op.drop_index('ix_tb_procedure_step_chapter_id', table_name='tb_procedure_step')
    op.drop_table('tb_procedure_step')
    op.drop_index('ix_tb_procedure_chapter_procedure_id_sort_order', table_name='tb_procedure_chapter')
    op.drop_index('ix_tb_procedure_chapter_parent_id', table_name='tb_procedure_chapter')
    op.drop_index('ix_tb_procedure_chapter_mark_status', table_name='tb_procedure_chapter')
    op.drop_index(op.f('ix_tb_procedure_chapter_is_active'), table_name='tb_procedure_chapter')
    op.drop_index(op.f('ix_tb_procedure_chapter_created_at'), table_name='tb_procedure_chapter')
    op.drop_index('ix_tb_procedure_chapter_content_type', table_name='tb_procedure_chapter')
    op.drop_table('tb_procedure_chapter')
    op.drop_index('ix_tb_procedure_attachment_storage_path', table_name='tb_procedure_attachment')
    op.drop_index('ix_tb_procedure_attachment_procedure_id', table_name='tb_procedure_attachment')
    op.drop_index(op.f('ix_tb_procedure_attachment_is_active'), table_name='tb_procedure_attachment')
    op.drop_index(op.f('ix_tb_procedure_attachment_created_at'), table_name='tb_procedure_attachment')
    op.drop_table('tb_procedure_attachment')
    op.drop_index('uq_tb_procedure_asset_reference_asset_id_procedure_id', table_name='tb_procedure_asset_reference')
    op.drop_index('ix_tb_procedure_asset_reference_procedure_id', table_name='tb_procedure_asset_reference')
    op.drop_index('ix_tb_procedure_asset_reference_asset_id', table_name='tb_procedure_asset_reference')
    op.drop_table('tb_procedure_asset_reference')
    op.drop_index(op.f('ix_tb_procedure_status'), table_name='tb_procedure')
    op.drop_index(op.f('ix_tb_procedure_procedure_group_id'), table_name='tb_procedure')
    op.drop_index(op.f('ix_tb_procedure_is_current'), table_name='tb_procedure')
    op.drop_index(op.f('ix_tb_procedure_is_active'), table_name='tb_procedure')
    op.drop_index(op.f('ix_tb_procedure_folder_id'), table_name='tb_procedure')
    op.drop_index(op.f('ix_tb_procedure_created_at'), table_name='tb_procedure')
    op.drop_table('tb_procedure')
    op.drop_index(op.f('ix_tb_folder_sequence_is_active'), table_name='tb_folder_sequence')
    op.drop_index(op.f('ix_tb_folder_sequence_folder_id'), table_name='tb_folder_sequence')
    op.drop_index(op.f('ix_tb_folder_sequence_created_at'), table_name='tb_folder_sequence')
    op.drop_table('tb_folder_sequence')
    op.drop_index(op.f('ix_tb_procedure_settings_is_active'), table_name='tb_procedure_settings')
    op.drop_index(op.f('ix_tb_procedure_settings_created_at'), table_name='tb_procedure_settings')
    op.drop_table('tb_procedure_settings')
    op.drop_index(op.f('ix_tb_procedure_field_is_active'), table_name='tb_procedure_field')
    op.drop_index(op.f('ix_tb_procedure_field_created_at'), table_name='tb_procedure_field')
    op.drop_table('tb_procedure_field')
    op.drop_index('ix_tb_procedure_audit_log_target_id_created_at', table_name='tb_procedure_audit_log')
    op.drop_index(op.f('ix_tb_procedure_audit_log_target_id'), table_name='tb_procedure_audit_log')
    op.drop_index(op.f('ix_tb_procedure_audit_log_procedure_group_id'), table_name='tb_procedure_audit_log')
    op.drop_index('ix_tb_procedure_audit_log_group_id_created_at', table_name='tb_procedure_audit_log')
    op.drop_index('ix_tb_procedure_audit_log_created_at', table_name='tb_procedure_audit_log')
    op.drop_index('ix_tb_procedure_audit_log_action_created_at', table_name='tb_procedure_audit_log')
    op.drop_table('tb_procedure_audit_log')
    op.drop_index(op.f('ix_tb_procedure_asset_is_active'), table_name='tb_procedure_asset')
    op.drop_index(op.f('ix_tb_procedure_asset_created_at'), table_name='tb_procedure_asset')
    op.drop_table('tb_procedure_asset')
    op.drop_index('ix_tb_folder_audit_log_target_id_created_at', table_name='tb_folder_audit_log')
    op.drop_index(op.f('ix_tb_folder_audit_log_target_id'), table_name='tb_folder_audit_log')
    op.drop_index('ix_tb_folder_audit_log_created_at', table_name='tb_folder_audit_log')
    op.drop_index('ix_tb_folder_audit_log_action_created_at', table_name='tb_folder_audit_log')
    op.drop_table('tb_folder_audit_log')
    op.drop_index(op.f('ix_tb_folder_parent_id'), table_name='tb_folder')
    op.drop_index(op.f('ix_tb_folder_is_active'), table_name='tb_folder')
    op.drop_index(op.f('ix_tb_folder_created_at'), table_name='tb_folder')
    op.drop_table('tb_folder')
    # ### end Alembic commands ###
